version: '3'

services:
    nginx:
        container_name: ${APP_NAME}.nginx
        image: nginx:1.20
        ports:
            - ${SERVER_PORT}:80
            - 443:443
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ${APP_SRC}:/var/www
        links: 
            - php
        
    php:
        container_name: ${APP_NAME}.php
        build: ./php
        volumes: 
            - ${APP_SRC}:/var/www
        links: 
            - mariadb
            - rabbitmq
            - mailhog
           
    mariadb:
        container_name: ${APP_NAME}.mariadb
        image: mariadb:10.6.7
        restart: always
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_USER}
        ports:
            - ${DB_PORT:-3306}:3306  
        volumes:
            - dbdata:/var/lib/mysql
            - ${APP_SRC}/etc/database:/var/www/database:ro

    rabbitmq:
        container_name: ${APP_NAME}.rabbitmq
        image: rabbitmq:3.11-management
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        ports:
            - ${RABBITMQ_PORT:-5672}:5672
            - ${RABBITMQ_ADMINPORT:-15672}:15672

    mailhog:
        container_name: ${APP_NAME}.mailhog
        image: mailhog/mailhog
        ports:
            - ${MAIL_WEB_PORT:-8025}:8025
            - ${MAIL_SMTP_PORT:-1025}:1025

volumes: 
    dbdata: